name: RSD CI

on:
    push:
        branches: [main]

jobs:
    super-lint:
        name: Lint code base
        runs-on: ubunto-latest
        steps:
          - name: Checkout code
            uses: action/checkout@v2
    